name: lambda
on:
    push:
        branches:
        - master
jobs:
    test:
        name: Testes de python
        uses: AlnDevE/reusable-workflow-lambda-python@master/.github/workflows/ci.yml@v1
        with:
            runs-on: 'ubuntu-latest'
      
        

