name: lambda
on:
    push:
        branches:
        - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Setup de pytohn
          uses: actions/setup-python@v3
          with:
            python-version: 3.8
        
        - name: Installing Dependencies
          run: pip install pytest

        - name: Run test
          run: python -m pytest /app

